"""Add category is_active and karat check

Revision ID: 024dfbf29071
Revises: f3f2a9c1bdce
Create Date: 2026-08-14 02:23:29.277593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024dfbf29071'
down_revision: Union[str, None] = 'f3f2a9c1bdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_check_constraint('check_supported_karat', 'gold_prices', 'karat IN (18, 21, 22, 24)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_supported_karat', 'gold_prices')
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
