"""sales_and_inventory_lock_phase_5

Revision ID: 0f6276a49deb
Revises: 2c9a923632fc
Create Date: 2026-08-14 03:24:31.133603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6276a49deb'
down_revision: Union[str, None] = '2c9a923632fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('locked_by_id', sa.Integer(), nullable=True))
    op.add_column('inventory_items', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_inventory_items_locked_by_id_users', 'inventory_items', 'users', ['locked_by_id'], ['id'])
    op.add_column('sales', sa.Column('idempotency_key', sa.String(), nullable=False))
    op.create_index(op.f('ix_sales_idempotency_key'), 'sales', ['idempotency_key'], unique=True)
    
    op.execute("CREATE SEQUENCE invoice_number_seq START 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_idempotency_key'), table_name='sales')
    op.drop_column('sales', 'idempotency_key')
    op.execute("DROP SEQUENCE invoice_number_seq")
    op.drop_constraint('fk_inventory_items_locked_by_id_users', 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'locked_at')
    op.drop_column('inventory_items', 'locked_by_id')
    # ### end Alembic commands ###
