"""Inventory phase 4

Revision ID: 2c9a923632fc
Revises: 024dfbf29071
Create Date: 2026-08-14 02:46:56.522521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9a923632fc'
down_revision: Union[str, None] = '024dfbf29071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS inventory_sku_seq START 1;')
    
    # Create the new enum type first
    op.execute("CREATE TYPE transactiontype AS ENUM ('STOCK_IN', 'LOCK', 'UNLOCK', 'ADJUST', 'SELL', 'RETURN');")
    
    op.add_column('inventory_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory_transactions', sa.Column('previous_status', sa.Enum('AVAILABLE', 'LOCKED', 'SOLD', 'RETURNED', name='itemstatus'), nullable=True))
    op.add_column('inventory_transactions', sa.Column('new_status', sa.Enum('AVAILABLE', 'LOCKED', 'SOLD', 'RETURNED', name='itemstatus'), nullable=False))
    op.add_column('inventory_transactions', sa.Column('historical_weight', sa.Numeric(precision=10, scale=3), nullable=False))
    op.add_column('inventory_transactions', sa.Column('historical_karat', sa.Integer(), nullable=False))
    op.add_column('inventory_transactions', sa.Column('historical_cost_basis', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('inventory_transactions', sa.Column('historical_manufacturing_fee', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('inventory_transactions', sa.Column('reference_type', sa.String(), nullable=True))
    op.execute('ALTER TABLE inventory_transactions ALTER COLUMN transaction_type TYPE transactiontype USING transaction_type::text::transactiontype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE inventory_transactions ALTER COLUMN transaction_type TYPE VARCHAR USING transaction_type::text')
    op.execute("DROP TYPE transactiontype;")
    op.drop_column('inventory_transactions', 'reference_type')
    op.drop_column('inventory_transactions', 'historical_manufacturing_fee')
    op.drop_column('inventory_transactions', 'historical_cost_basis')
    op.drop_column('inventory_transactions', 'historical_karat')
    op.drop_column('inventory_transactions', 'historical_weight')
    op.drop_column('inventory_transactions', 'new_status')
    op.drop_column('inventory_transactions', 'previous_status')
    op.drop_column('inventory_items', 'updated_at')
    
    op.execute('DROP SEQUENCE IF EXISTS inventory_sku_seq;')
    # ### end Alembic commands ###
