"""add_reservation_and_update_item_status

Revision ID: 3398a4814ae1
Revises: 5f76fc28357f
Create Date: 2026-08-16 01:51:38.233337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3398a4814ae1'
down_revision: Union[str, None] = '5f76fc28357f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Data migration: Force all existing LOCKED items back to AVAILABLE
    op.execute("UPDATE inventory_items SET status = 'AVAILABLE' WHERE status = 'LOCKED'")
    op.execute("UPDATE inventory_transactions SET previous_status = 'AVAILABLE' WHERE previous_status = 'LOCKED'")
    op.execute("UPDATE inventory_transactions SET new_status = 'AVAILABLE' WHERE new_status = 'LOCKED'")
    
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id')
    )
    op.create_index(op.f('ix_reservations_expires_at'), 'reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_reservations_session_id'), 'reservations', ['session_id'], unique=False)
    op.drop_constraint('fk_inventory_items_locked_by_id_users', 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'locked_at')
    op.drop_column('inventory_items', 'locked_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('locked_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_inventory_items_locked_by_id_users', 'inventory_items', 'users', ['locked_by_id'], ['id'])
    op.drop_index(op.f('ix_reservations_session_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_expires_at'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
