"""add_customer_phone_unique_index

Revision ID: 5f76fc28357f
Revises: 0f6276a49deb
Create Date: 2026-08-14 14:20:55.543436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f76fc28357f'
down_revision: Union[str, None] = '0f6276a49deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customers_phone_unique', 'customers', ['phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_phone_unique', table_name='customers', postgresql_where=sa.text('phone IS NOT NULL'))
    # ### end Alembic commands ###
